# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/yogio/OneDrive/Desktop/INF3500/labo-5-ma-2164587_2393842/xdc/PYNQ-Z2-v1.0.xdc

# Block Designs: bd/zynq/zynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_proc_sys_reset_0_0/zynq_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_dma_0_0/zynq_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_dma_0_0 || ORIG_REF_NAME==zynq_axi_dma_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_ps7_0_axi_periph_imp_auto_pc_0/zynq_ps7_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps7_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==zynq_ps7_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_ps7_0_axi_periph_0/zynq_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_mem_intercon_imp_auto_pc_0/zynq_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==zynq_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_mem_intercon_imp_auto_us_0/zynq_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==zynq_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_mem_intercon_0/zynq_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_mem_intercon_0 || ORIG_REF_NAME==zynq_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_mem_intercon_1_imp_auto_pc_0/zynq_axi_mem_intercon_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_mem_intercon_1_imp_auto_pc_0 || ORIG_REF_NAME==zynq_axi_mem_intercon_1_imp_auto_pc_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_mem_intercon_1_imp_auto_us_0/zynq_axi_mem_intercon_1_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_mem_intercon_1_imp_auto_us_0 || ORIG_REF_NAME==zynq_axi_mem_intercon_1_imp_auto_us_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_mem_intercon_1_0/zynq_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_mem_intercon_1_0 || ORIG_REF_NAME==zynq_axi_mem_intercon_1_0} -quiet] -quiet

# XDC: c:/Users/yogio/OneDrive/Desktop/INF3500/laboratoire5/laboratoire5.gen/sources_1/bd/zynq/zynq_ooc.xdc
