# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yogio/OneDrive/Desktop/INF3500/laboratoire3/laboratoire3.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_0/zynq_axi_gpio_0_0.xci
# IP: The module: 'zynq_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yogio/OneDrive/Desktop/INF3500/laboratoire3/laboratoire3.gen/sources_1/bd/zynq/ip/zynq_axi_gpio_0_0/zynq_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/yogio/OneDrive/Desktop/INF3500/laboratoire3/laboratoire3.gen/sources_1/bd/zynq/ip/zynq_axi_gpio_0_0/zynq_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/yogio/OneDrive/Desktop/INF3500/laboratoire3/laboratoire3.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_0/zynq_axi_gpio_0_0.xci
# IP: The module: 'zynq_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yogio/OneDrive/Desktop/INF3500/laboratoire3/laboratoire3.gen/sources_1/bd/zynq/ip/zynq_axi_gpio_0_0/zynq_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/yogio/OneDrive/Desktop/INF3500/laboratoire3/laboratoire3.gen/sources_1/bd/zynq/ip/zynq_axi_gpio_0_0/zynq_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
